Fixes error downloading tarball for git-script recipe
system Ruby and OpenSSL that ships with OSX 10.12.x throws an error when talking to Github due to recent changes in Github:

```
ERROR: SSL Error connecting to https://github.com/pivotal/git_scripts/tarball/master
ERROR: SSL Validation failure connecting to host: github.com - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
...

    ================================================================================
    Error executing action `create` on resource 'remote_file[/var/chef/cache/git_scripts.tgz]'
    ================================================================================

    OpenSSL::SSL::SSLError
    ----------------------
    SSL Error connecting to https://github.com/pivotal/git_scripts/tarball/master - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
```